version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python-development-dependencies:
        dependency-type: development
      python-runtime-dependencies:
        dependency-type: production
